spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/construction_monitoring
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET:very-strong-secret-key-for-production-use-only-change-this-in-production}
    expiration-ms: 86400000
  upload:
    dir: uploads
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}
  bootstrap:
    admin:
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}
